name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
          moodle-plugin-ci add-config "\$CFG->behat_snapshots_path = '`pwd`/moodle/local/behatsnapshots/snapshots';"
        env:
          DB: pgsql
          MOODLE_BRANCH: MOODLE_401_STABLE

      - name: PHP Lint
        run: moodle-plugin-ci phplint

      - name: PHP Mess Detector
        run: moodle-plugin-ci phpmd

      - name: Validating
        run: moodle-plugin-ci validate

      - name: Behat features
        run: moodle-plugin-ci behat

      - name: Upload Snapshot failures
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: snapshot_failures
          path: moodle/local/behatsnapshots/snapshots/failures/*
